GITHUB_TOKEN: ENC[AES256_GCM,data:BJdiog0m8wvaotA4YvH4fV/CsCEwW9bCpiDqsQ309uF3KobEvHC7aw==,iv:ofKybtCLAOaXyw27TLGrDmSLVgoAVqCvr4jhkeOXhAk=,tag:+HFCVVZJyru+LbfTAbxgZQ==,type:str]
sops:
    age:
        - recipient: age1595c6n7r3zu0aql8qeehlulds6g4cvavmphsyauk9uddks5hpuzqcg7c4u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZ0lIc2g1TTlRZzBvYzhP
            bzk4K0J5ait1YmZMYlNyK2t5NVRBSmsvTVNRCkhmN3dRSzFlMnJlZEt3MTFRM1Zo
            dlQ3dmI1RC9pRVF6bEo4MkpJQjVyRzAKLS0tIHNqMjdLS3VuTmVuK3pIYlZMTU8v
            VGp2QStxSW5jOFRvOHg1d3BiQ3ZDVHcKigSjxlhPb6iPGxzIxXG1Wa5ugcL8hrhI
            7pwwgczFgWKySdtclgsz8btI70qZu4FPGe2Q94adD+2B1MslIwHiHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T16:01:56Z"
    mac: ENC[AES256_GCM,data:Mg+gAqWWlMaNIUBGIOh80nFuzDatyToDJn79Sp7sowIGsi0zzcRMz3m1HmyBBZqehWzR53mq1O9dfEDwcG+qXQzqvUGtATnTs/DHBXMr2cmu7GtIWBAWWpUcXNylEKHUIiagP7WXTFBDfwQXTdO4HT96G1XZRGcsIFZDB50JqzM=,iv:AqoZduadA3sQoiUAOx6Hj8I0bVibrFV6/kv8o69Rh4w=,tag:oihuikjYxEcNcKwVUY5fKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
